name: 🧪 Test & Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    name: 🧪 tests
    runs-on: ubuntu-latest
    steps:
      - name: 🛠️ Prepare pnpm workspace
        uses: dyne/pnpm@main
        with:
          node-version: 20
          pnpm-version: 9
      - name: Chrome browser for testing
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
      - name: 🧪 Run the tests
        run: pnpm run test
        env: 
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

  docs:
    name: 📖 docs
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 🛠️ Prepare pnpm workspace
        uses: dyne/pnpm@main
        with:
          node-version: 20
          pnpm-version: 9
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install
          build_command: pnpm run build && pnpm run build-storybook
          path: storybook-static
